sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6

install:
  - composer self-update --no-interaction
  - composer install --no-interaction --prefer-dist

script:
    - composer run test