name: Build assets
on:
  push:
    branches:
      - master
      - test-docs

jobs:
  build:
    name: Build documents
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install dependencies
      run: |
        npm ci

    - name: Generate hookdoc
      run: |
        npm run doc

    - name: Generate PHP API docs
      uses: docker://phpdoc/phpdoc:3
      with:
        args: run --title ClarksonCore --visibility public --sourcecode -d src -t out/phpdoc

    - name: Publish pages
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: "out/"
        GH_PAT: ${{ secrets.GH_PAT }}
